site_name: Design Patterns
repo_url: https://github.com/carmo-sousa/DesignPatterns
repo_name: carmo-sousa/DesignPatterns

theme:
  name: material
  language: pt-BR
  # font:
  #   text: Noto Serif
  icon:
    repo: material/github

plugins:
  - search:
  - tags:
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          load_external_modules: false
          options:
            show_bases: true
            show_source: false
            parameter_headings: true
